# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d18b5d08db6f4873cb87c8dfef68663657f3da097a5c693c7aeae32df5e5323f39165338ca22a46d32e828006806ad23eb8208ebd6afad64175afcb20eac1d8f

test:
  secret_key_base: 2656937d1d4e9c3e4c36193786e36289d394df865d2d619da8d2b6d2d0942521915b422cefe7a5551a2ff7ebff9f2b2bbd104836024ab122c14237d1033e3f7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
